// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// svds_XmD
SEXP svds_XmD(SEXP X, SEXP mu, SEXP D, int k);
RcppExport SEXP _fad_svds_XmD(SEXP XSEXP, SEXP muSEXP, SEXP DSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mu(muSEXP);
    Rcpp::traits::input_parameter< SEXP >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(svds_XmD(X, mu, D, k));
    return rcpp_result_gen;
END_RCPP
}
// postmdiag
NumericMatrix postmdiag(NumericMatrix X, NumericVector d);
RcppExport SEXP _fad_postmdiag(SEXP XSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(postmdiag(X, d));
    return rcpp_result_gen;
END_RCPP
}
// colSumSqdgC
NumericVector colSumSqdgC(S4 X, NumericVector D, NumericVector mu);
RcppExport SEXP _fad_colSumSqdgC(SEXP XSEXP, SEXP DSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(colSumSqdgC(X, D, mu));
    return rcpp_result_gen;
END_RCPP
}
// colSumSq
NumericVector colSumSq(NumericMatrix X, NumericVector D, NumericVector mu);
RcppExport SEXP _fad_colSumSq(SEXP XSEXP, SEXP DSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(colSumSq(X, D, mu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fad_svds_XmD", (DL_FUNC) &_fad_svds_XmD, 4},
    {"_fad_postmdiag", (DL_FUNC) &_fad_postmdiag, 2},
    {"_fad_colSumSqdgC", (DL_FUNC) &_fad_colSumSqdgC, 3},
    {"_fad_colSumSq", (DL_FUNC) &_fad_colSumSq, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
