# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ERF <- function(P, Mu, Sigma) {
    .Call(`_fad_ERF`, P, Mu, Sigma)
}

eigs_sym_RXmD <- function(Xmat, mu, D, er, vr, ybar, nev, matclass) {
    .Call(`_fad_eigs_sym_RXmD`, Xmat, mu, D, er, vr, ybar, nev, matclass)
}

.postmdiag <- function(X, d) {
    .Call(`_fad_postmdiag`, X, d)
}

.icolSumSqdgC <- function(X, D, mu) {
    .Call(`_fad_colSumSqdgC`, X, D, mu)
}

.icolSumSq <- function(X, D, mu) {
    .Call(`_fad_colSumSq`, X, D, mu)
}

RXM <- function(X, ER) {
    .Call(`_fad_RXM_CC`, X, ER)
}

cmdg <- function(L, D) {
    .Call(`_fad_cmdg_CC`, L, D)
}

taom <- function(X, L, D, mu, cmatdg) {
    .Call(`_fad_taom_CC`, X, L, D, mu, cmatdg)
}

ism <- function(X, L, D, mu, cmatdg) {
    .Call(`_fad_ism_CC`, X, L, D, mu, cmatdg)
}

mSD <- function(X, mu, D, ER, VR, ybar) {
    .Call(`_fad_mSD_CC`, X, mu, D, ER, VR, ybar)
}

