# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigs_sym_RXmD <- function(Xmat, mu, D, er, vr, ybar, nev, matclass) {
    .Call(`_fad_eigs_sym_RXmD`, Xmat, mu, D, er, vr, ybar, nev, matclass)
}

.postmdiag <- function(X, d) {
    .Call(`_fad_postmdiag`, X, d)
}

.icolSumSqdgC <- function(X, D, mu) {
    .Call(`_fad_colSumSqdgC`, X, D, mu)
}

.icolSumSq <- function(X, D, mu) {
    .Call(`_fad_colSumSq`, X, D, mu)
}

