# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svds_XmD <- function(X, mu, D, k) {
    .Call(`_fad_svds_XmD`, X, mu, D, k)
}

.postmdiag <- function(X, d) {
    .Call(`_fad_postmdiag`, X, d)
}

.icolSumSqdgC <- function(X, D, mu) {
    .Call(`_fad_colSumSqdgC`, X, D, mu)
}

.icolSumSq <- function(X, D, mu) {
    .Call(`_fad_colSumSq`, X, D, mu)
}

